# Generated by Django 3.2.9 on 2021-11-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='static/images')),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=100)),
                ('offer', models.BooleanField(default=False)),
            ],
        ),
    ]
