# Generated by Django 3.2.9 on 2022-01-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.EmailField(max_length=100)),
                ('gender', models.CharField(max_length=6)),
                ('intrest', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=20)),
                ('feedback', models.CharField(max_length=200)),
            ],
        ),
    ]
